# Add 'branding' to any file changes within 'switchbot' folder
branding: image/*

# Add 'enhancement' label to any change to index.js file
enhancement:
  - src/*
  - package.json
  - pakcage-lock.json
  - config.schema.json

# Add 'workflow' to any changes within 'workflow' folder or any subfolders
workflow:
  - .github/workflows/*

beta:
- base-branch: 'beta*'

alpha:
- base-branch: 'alpha*'

latest:
- base-branch: 'latest'