name: Release Drafter

on:
  workflow_call:
    secrets:
      token:
        description: 'The GitHub Token'
        required: true

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6.0.0-beta.1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
